### ISSUE TITLE
Profile comment submissions & node previews - find out why so much memory is used

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/forum.backdropcms.org#68] opened 2018-10-05 20:23 UTC
Follow up to https://github.com/backdrop-ops/forum.backdropcms.org/issues/67#issuecomment-427368940

> We got a complaint on twitter about exceeding the PHP memory limit when saving comments:
twitter.com/lourdas_v/status/1046323847526535168  I can report that I have been able to reproduce this problem. Perhaps we should bump it?

**Comment by jenlampton** [comment] 2018-11-02 20:43
There are new comments on https://github.com/backdrop-ops/forum.backdropcms.org/issues/67 about this issue from @stpaultim

> Just want to report that I just experienced the same problem while previewing comments in the forum. and was able to reproduce it multiple times. I was able to SAVE my comments without any problem.

> "Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 130968 bytes) in /home/forum/repo/www/core/includes/bootstrap.inc on line 3175"

> Any other ideas?

**Comment by larsdesigns** [comment] 2018-11-03 10:08
I doubled the allocated memory again and I also increased APC memory to 512 from 128.

I feel like we should examine the summit function(s) for the forms that are exhausting the memory.

**Comment by jenlampton** [comment] 2018-11-05 19:56
Comment from @lourdas on https://github.com/backdrop-ops/forum.backdropcms.org/issues/67

> Today, I also got a Fatal error: Maximum execution time of 30 seconds exceeded in /home/forum/repo/www/core/modules/ckeditor/ckeditor.module on line 712 error. It seems that previewing a comment is almost impossible.

**Comment by stpaultim** [comment] 2018-11-17 02:20
_Looks like I was commenting on the wrong issue, cutting and pasting this from #67:_

> Looks like this is happening with new forum posts as well. It came up in forum over the last couple of days/weeks.
> https://forum.backdropcms.org/forum/forum-preview-throws-error
> https://forum.backdropcms.org/forum/errors-when-submitting-forum-topics

**Comment by jenlampton** [comment] 2018-12-07 00:21
For now, I have added `#access = FALSE` to the preview button. It's a hack, but it should stop people form loosing their content.

**Comment by stpaultim** [comment] 2018-12-16 01:00
Thanks @hosef for looking into this, but I think it's still an issue. I just tried previewing a comment and got a memory error and when I tried to preview a test forum topic I got a Page not Found error (I am not sure if this is the same problem or a different problem - should I open a new tickete)?

![page_not_found___backdrop_forum](https://user-images.githubusercontent.com/3144571/50048851-8d2d5500-009b-11e9-9a47-80a5cd1ffd77.png)

**Comment by stpaultim** [comment] 2018-12-16 01:04
OK, after more research. Different things happen in different situations:

1) Preview on creation of a new comment - works fine

2) Preview while editing a new comment - "Fatal error: Maximum execution time of 30 seconds exceeded in /home/forum/repo/www/core/modules/field/field.attach.inc on line 616"

3) Preview while creating a new topic - "page not found"

**Comment by jenlampton** [comment] 2018-12-27 21:01
@hosef do you have time to look into this?

**Comment by hosef** [comment] 2018-12-31 17:31
2. @stpaultim I am not able to reproduce this. Could you let me know how you found this?

3. I think this is a core issue. If you manually change the preview URL from `forum_topic` to `forum-topic`, so I don't think the node module is properly handling node types with an `_` in them. This was probably caused with the rework to node previews that happened recently.

**Comment by hosef** [comment] 2018-12-31 17:46
I just checked, and 3 is fixed in the latest version of Backdrop. #3336

**Comment by lourdas** [comment] 2018-12-31 19:01
I'm 3 hours away from 2019 (here...) and you're committing code people? :)

Happy New Year everyone! I hope Backdrop will gain more audience and more developers for a better CMS!

**Comment by jenlampton** [comment] 2018-12-31 20:30
> and you're committing code people? :)

Whenever there's a spare moment! 

> Happy New Year everyone! I hope Backdrop will gain more audience and more developers for a better CMS!

yes, Happy NYE to all! (and I wish for the same!)

**Comment by stpaultim** [comment] 2018-12-31 20:33
[Item #2](https://github.com/backdrop-ops/forum.backdropcms.org/issues/68#issuecomment-447609627) is still generating the `Fatal error: Maximum execution time of 30 seconds exceeded in /home/forum/repo/www/core/includes/database/database.inc on line 826` message for me. 

Steps to reproduce:
1) Comment on an topic in the forum
2) Try to `edit` your comment
3) While in edit mode, try to `preview` your changes. 

I can no longer recreate this problem - `3) Preview while creating a new topic - "page not found"`

**Comment by stpaultim** [comment] 2018-12-31 20:38
@jenlampton - In regard to our conversation during the meeting last week. This seems like a edge case and probably does not warrant turning off the `preview` option for now (in my opinion). However, I think it is something we need to try and fix. It does not put Backdrop in a good light if you get errors while trying to use the site and ask questions.

**Comment by jenlampton** [comment] 2018-12-31 20:45
> it is something we need to try and fix 

Yes of course. But should we disable comment preview until it's fixed?

**Comment by stpaultim** [comment] 2018-12-31 20:49
I tried it multiple times on multiple different topics. Short topics and long topics. As a moderator, I also tried it while editing a comment that was not my own. Same result every time.

**Comment by hosef** [comment] 2019-01-01 01:12
So, it turns out this is the same issue as I originally fixed. I made a pull request that should fix it, but the change seems really hackish. If anyone has a suggestion to improve it, that would be great.

**Comment by jenlampton** [comment] 2019-01-01 18:03
Thanks @hosef,
I've merged your PR to resolve the issue, but added a @todo comment so we can revisit that approach later, if needed.

**Closed** 2019-11-10 01:35 UTC
